services:
  - type: web
    name: raven-shop-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    plan: free
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DATABASE_URL
        value: postgresql://ravenshop_db_user:nEeZ5MHoo5eEw7FLarHegSv4BNlY6Ovj@dpg-d08sks9r0fns73doqolg-a/ravenshop_db
    branches:
      - main
  
  - type: pserv
    name: ravenshop-db
    env: postgresql
    plan: free
    user: postgres
    ipAllowList: []
