services:
  - type: web
    name: raven-shop-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    plan: free
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DATABASE_URL
        value: postgresql://ravenshop-db_owner:npg_GMzymHeF1a7j@ep-lingering-tooth-a88ay494-pooler.eastus2.azure.neon.tech/ravenshop-db?sslmode=require
    branches:
      - main
  
  - type: pserv
    name: ravenshop-db
    env: postgresql
    plan: free
    user: postgres
    ipAllowList: []
